/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabasev4.pkg0;



/**
 *
 * @author Samuel
 */


import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class MainMenu extends javax.swing.JFrame {
    

    /**
     * Creates new form MainMenu
     */
    
    DefaultTableModel model;
    
    public MainMenu() {
        initComponents();
        model = (DefaultTableModel)mainTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel2 = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JButton();
        viewDatabaseSubtitle = new javax.swing.JLabel();
        viewEmployeeDataSubtitle = new javax.swing.JLabel();
        infoLabel3 = new javax.swing.JLabel();
        employeeInfoField = new javax.swing.JTextField();
        employeeNumberLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        fetchedDataPanel = new javax.swing.JPanel();
        printTable = new javax.swing.JButton();
        clearTable = new javax.swing.JButton();
        clearDatabaseButton = new javax.swing.JButton();
        updateTableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Employee Management System");

        infoLabel1.setText("Welcome to the Employee Management System (EMS), Version 3.0!");

        infoLabel2.setText("You add new employees to the system by clicking \"Add Employee\" on the right, or edit existing ones below.");

        addEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        viewDatabaseSubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewDatabaseSubtitle.setText("View Database");

        viewEmployeeDataSubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewEmployeeDataSubtitle.setText("View Employee Data");

        infoLabel3.setText("You can search for and edit employees by entering their employee number down below:");

        employeeInfoField.setText("######");
        employeeInfoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeInfoFieldFocusGained(evt);
            }
        });
        employeeInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInfoFieldActionPerformed(evt);
            }
        });

        employeeNumberLabel.setText("Employee Number:");

        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Location", "Work Status"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        fetchedDataPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        printTable.setText("Print Table");
        printTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTableActionPerformed(evt);
            }
        });

        clearTable.setText("ClearTable");
        clearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fetchedDataPanelLayout = new javax.swing.GroupLayout(fetchedDataPanel);
        fetchedDataPanel.setLayout(fetchedDataPanelLayout);
        fetchedDataPanelLayout.setHorizontalGroup(
            fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fetchedDataPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearTable)
                    .addComponent(printTable))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        fetchedDataPanelLayout.setVerticalGroup(
            fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fetchedDataPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(printTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearTable)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        clearDatabaseButton.setText("Clear Database");
        clearDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDatabaseButtonActionPerformed(evt);
            }
        });

        updateTableButton.setText("Update Table");
        updateTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewDatabaseSubtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewEmployeeDataSubtitle)
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(employeeNumberLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(employeeInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(402, 402, 402)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(fetchedDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel2)
                            .addComponent(infoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearDatabaseButton)
                            .addComponent(updateTableButton))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel)
                    .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel1)
                    .addComponent(clearDatabaseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel2)
                    .addComponent(updateTableButton))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDatabaseSubtitle)
                    .addComponent(viewEmployeeDataSubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeNumberLabel)
                            .addComponent(employeeInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fetchedDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // Add employee
        AddEmployee newWindow = new AddEmployee();
        newWindow.setVisible(true);
        System.out.println("Opened AddEmployee");
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void employeeInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeInfoFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void employeeInfoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeInfoFieldFocusGained
        // Make the "######" Disappear when selected
        employeeInfoField.setText("");
    }//GEN-LAST:event_employeeInfoFieldFocusGained

    private void clearDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDatabaseButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getAllEmployees();
        
        for(EmployeeInfo emp : empList) {
            EmployeeDatabase.getInstance().removeEmployee(emp);
        }
    }//GEN-LAST:event_clearDatabaseButtonActionPerformed

    private void updateTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTableButtonActionPerformed
        // TODO add your handling code here:
        // model.insertRow(model.getRowCount(), new Object[]{"One", "Two", "Three", "Four", });
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getAllEmployees();
        
        clearTable();
        
        for(EmployeeInfo emp : empList) {
            Object[] row = new Object[5];
            row[0] = String.valueOf(emp.getEmployeeNumber());
            row[1] = emp.getFirstName();
            row[2] = emp.getLastName();
            row[3] = emp.getWorkLocation();
            row[4] = emp.getDepartment();
            addRowToTable(row);
        }
    }//GEN-LAST:event_updateTableButtonActionPerformed

    private void printTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTableActionPerformed
        // TODO add your handling code here:
        EmployeeDatabase.getInstance().printHashTable();
    }//GEN-LAST:event_printTableActionPerformed

    private void clearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTableActionPerformed
        // TODO add your handling code here:
        clearTable();
    }//GEN-LAST:event_clearTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.setRowCount(0);
        mainTable.setModel(model);
    }
    
    public void addRowToTable(Object[] row) {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.addRow(row);
        mainTable.setModel(model);   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton clearDatabaseButton;
    private javax.swing.JButton clearTable;
    private javax.swing.JTextField employeeInfoField;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JPanel fetchedDataPanel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton printTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateTableButton;
    private javax.swing.JLabel viewDatabaseSubtitle;
    private javax.swing.JLabel viewEmployeeDataSubtitle;
    // End of variables declaration//GEN-END:variables
}
