/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabasev4.pkg0;



/**
 *
 * @author Samuel
 */


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class MainMenu extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public MainMenu() {
        initComponents();
        model = (DefaultTableModel)mainTable.getModel();
        grayOutFetchedDataPanel();
        
        setTitle("Employee Database Version 4.4");
    }
    
    String employeeNumber;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel2 = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JButton();
        viewDatabaseSubtitle = new javax.swing.JLabel();
        viewEmployeeDataSubtitle = new javax.swing.JLabel();
        infoLabel3 = new javax.swing.JLabel();
        searchEmployeeInfoField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        fetchedDataPanel = new javax.swing.JPanel();
        fetchedPersonalDetailsPanel = new javax.swing.JPanel();
        fPDP1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        fPDP2 = new javax.swing.JPanel();
        fetchedFirstNameLabel = new javax.swing.JLabel();
        fetchedLastNameLabel = new javax.swing.JLabel();
        fetchedBirthdayLabel = new javax.swing.JLabel();
        fetchedWorkDetailsPanel = new javax.swing.JPanel();
        fWoDP1 = new javax.swing.JPanel();
        employeeNumberLabel = new javax.swing.JLabel();
        workLocationLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        fWoDP2 = new javax.swing.JPanel();
        fetchedEmployeeNumberLabel = new javax.swing.JLabel();
        fetchedWorkLocationLabel = new javax.swing.JLabel();
        fetchedDepartmentLabel = new javax.swing.JLabel();
        fetchedWagelDetailsPanel = new javax.swing.JPanel();
        fWaDP1 = new javax.swing.JPanel();
        typeOfWorkLabel = new javax.swing.JLabel();
        hourlyWageLabel = new javax.swing.JLabel();
        hoursPerWeekLabel = new javax.swing.JLabel();
        weeksPerYearLabel = new javax.swing.JLabel();
        deductionRateLabel = new javax.swing.JLabel();
        grossYearlySalaryLabel = new javax.swing.JLabel();
        netYearlySalaryLabel = new javax.swing.JLabel();
        fWaDP2 = new javax.swing.JPanel();
        fetchedTypeOfWorkLabel = new javax.swing.JLabel();
        fetchedHourlyWageLabel = new javax.swing.JLabel();
        fetchedHoursPerWeekLabel = new javax.swing.JLabel();
        fetchedWeeksPerYearLabel = new javax.swing.JLabel();
        fetchedDeductionRateLabel = new javax.swing.JLabel();
        fetchedGrossYearlySalaryLabel = new javax.swing.JLabel();
        fetchedNetYearlySalaryLabel = new javax.swing.JLabel();
        editEmployeeButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        clearDatabaseButton = new javax.swing.JButton();
        updateTableButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Employee Management System");

        infoLabel1.setText("Welcome to the Employee Management System (EMS), Version 4.4!");

        infoLabel2.setText("You add new employees to the system by clicking \"Add Employee\" on the right, or edit existing ones below.");

        addEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        viewDatabaseSubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewDatabaseSubtitle.setText("View Database");

        viewEmployeeDataSubtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewEmployeeDataSubtitle.setText("View Employee Data");

        infoLabel3.setText("You can search for and edit employees by entering their employee number down below:");

        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Num", "First Name", "Last Name", "Location", "Department"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        fetchedDataPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fetchedPersonalDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        birthdayLabel.setText("Birthday:");

        javax.swing.GroupLayout fPDP1Layout = new javax.swing.GroupLayout(fPDP1);
        fPDP1.setLayout(fPDP1Layout);
        fPDP1Layout.setHorizontalGroup(
            fPDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fPDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(birthdayLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fPDP1Layout.setVerticalGroup(
            fPDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPDP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthdayLabel)
                .addContainerGap())
        );

        fetchedFirstNameLabel.setText(" ");

        fetchedLastNameLabel.setText(" ");

        fetchedBirthdayLabel.setText(" ");

        javax.swing.GroupLayout fPDP2Layout = new javax.swing.GroupLayout(fPDP2);
        fPDP2.setLayout(fPDP2Layout);
        fPDP2Layout.setHorizontalGroup(
            fPDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPDP2Layout.createSequentialGroup()
                .addGroup(fPDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fetchedFirstNameLabel)
                    .addComponent(fetchedLastNameLabel)
                    .addComponent(fetchedBirthdayLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fPDP2Layout.setVerticalGroup(
            fPDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fetchedFirstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedLastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedBirthdayLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fetchedPersonalDetailsPanelLayout = new javax.swing.GroupLayout(fetchedPersonalDetailsPanel);
        fetchedPersonalDetailsPanel.setLayout(fetchedPersonalDetailsPanelLayout);
        fetchedPersonalDetailsPanelLayout.setHorizontalGroup(
            fetchedPersonalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fetchedPersonalDetailsPanelLayout.createSequentialGroup()
                .addComponent(fPDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fPDP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fetchedPersonalDetailsPanelLayout.setVerticalGroup(
            fetchedPersonalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fetchedPersonalDetailsPanelLayout.createSequentialGroup()
                .addComponent(fPDP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(fPDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fetchedWorkDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        employeeNumberLabel.setText("Employee Number:");

        workLocationLabel.setText("Work Location:");

        departmentLabel.setText("Department:");

        javax.swing.GroupLayout fWoDP1Layout = new javax.swing.GroupLayout(fWoDP1);
        fWoDP1.setLayout(fWoDP1Layout);
        fWoDP1Layout.setHorizontalGroup(
            fWoDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWoDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fWoDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeNumberLabel)
                    .addComponent(workLocationLabel)
                    .addComponent(departmentLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fWoDP1Layout.setVerticalGroup(
            fWoDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fWoDP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workLocationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentLabel)
                .addContainerGap())
        );

        fetchedEmployeeNumberLabel.setText(" ");

        fetchedWorkLocationLabel.setText(" ");

        fetchedDepartmentLabel.setText(" ");

        javax.swing.GroupLayout fWoDP2Layout = new javax.swing.GroupLayout(fWoDP2);
        fWoDP2.setLayout(fWoDP2Layout);
        fWoDP2Layout.setHorizontalGroup(
            fWoDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWoDP2Layout.createSequentialGroup()
                .addGroup(fWoDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fetchedEmployeeNumberLabel)
                    .addComponent(fetchedWorkLocationLabel)
                    .addComponent(fetchedDepartmentLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fWoDP2Layout.setVerticalGroup(
            fWoDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWoDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fetchedEmployeeNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedWorkLocationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedDepartmentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fetchedWorkDetailsPanelLayout = new javax.swing.GroupLayout(fetchedWorkDetailsPanel);
        fetchedWorkDetailsPanel.setLayout(fetchedWorkDetailsPanelLayout);
        fetchedWorkDetailsPanelLayout.setHorizontalGroup(
            fetchedWorkDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fetchedWorkDetailsPanelLayout.createSequentialGroup()
                .addComponent(fWoDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fWoDP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fetchedWorkDetailsPanelLayout.setVerticalGroup(
            fetchedWorkDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fWoDP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fWoDP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fetchedWagelDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wage Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        typeOfWorkLabel.setText("Type of Work:");

        hourlyWageLabel.setText("Hourly Wage:");

        hoursPerWeekLabel.setText("Hours per Week:");

        weeksPerYearLabel.setText("Weeks per Year:");

        deductionRateLabel.setText("Deduction Rate:");

        grossYearlySalaryLabel.setText("Gross Yearly Salary:");

        netYearlySalaryLabel.setText("Net Yearly Salary:");

        javax.swing.GroupLayout fWaDP1Layout = new javax.swing.GroupLayout(fWaDP1);
        fWaDP1.setLayout(fWaDP1Layout);
        fWaDP1Layout.setHorizontalGroup(
            fWaDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWaDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fWaDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeOfWorkLabel)
                    .addComponent(hourlyWageLabel)
                    .addComponent(hoursPerWeekLabel)
                    .addComponent(weeksPerYearLabel)
                    .addComponent(deductionRateLabel)
                    .addComponent(grossYearlySalaryLabel)
                    .addComponent(netYearlySalaryLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fWaDP1Layout.setVerticalGroup(
            fWaDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fWaDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeOfWorkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyWageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoursPerWeekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weeksPerYearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductionRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grossYearlySalaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netYearlySalaryLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        fetchedTypeOfWorkLabel.setText(" ");

        fetchedHourlyWageLabel.setText(" ");

        fetchedHoursPerWeekLabel.setText(" ");

        fetchedWeeksPerYearLabel.setText(" ");

        fetchedDeductionRateLabel.setText(" ");

        fetchedGrossYearlySalaryLabel.setText(" ");

        fetchedNetYearlySalaryLabel.setText(" ");

        javax.swing.GroupLayout fWaDP2Layout = new javax.swing.GroupLayout(fWaDP2);
        fWaDP2.setLayout(fWaDP2Layout);
        fWaDP2Layout.setHorizontalGroup(
            fWaDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWaDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fWaDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fetchedTypeOfWorkLabel)
                    .addComponent(fetchedHourlyWageLabel)
                    .addComponent(fetchedHoursPerWeekLabel)
                    .addComponent(fetchedWeeksPerYearLabel)
                    .addComponent(fetchedNetYearlySalaryLabel)
                    .addGroup(fWaDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fetchedGrossYearlySalaryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fetchedDeductionRateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fWaDP2Layout.setVerticalGroup(
            fWaDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fWaDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fetchedTypeOfWorkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedHourlyWageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedHoursPerWeekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedWeeksPerYearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedDeductionRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedGrossYearlySalaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedNetYearlySalaryLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fetchedWagelDetailsPanelLayout = new javax.swing.GroupLayout(fetchedWagelDetailsPanel);
        fetchedWagelDetailsPanel.setLayout(fetchedWagelDetailsPanelLayout);
        fetchedWagelDetailsPanelLayout.setHorizontalGroup(
            fetchedWagelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fetchedWagelDetailsPanelLayout.createSequentialGroup()
                .addComponent(fWaDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fWaDP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fetchedWagelDetailsPanelLayout.setVerticalGroup(
            fetchedWagelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fWaDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fWaDP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editEmployeeButton.setText("Edit Employee");
        editEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setText("Remove Employee");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fetchedDataPanelLayout = new javax.swing.GroupLayout(fetchedDataPanel);
        fetchedDataPanel.setLayout(fetchedDataPanelLayout);
        fetchedDataPanelLayout.setHorizontalGroup(
            fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fetchedDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fetchedPersonalDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fetchedWorkDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fetchedWagelDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fetchedDataPanelLayout.createSequentialGroup()
                        .addComponent(editEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(removeEmployeeButton)))
                .addContainerGap())
        );
        fetchedDataPanelLayout.setVerticalGroup(
            fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fetchedDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fetchedPersonalDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedWorkDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fetchedWagelDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(fetchedDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEmployeeButton)
                    .addComponent(editEmployeeButton))
                .addContainerGap())
        );

        clearDatabaseButton.setText("Clear Database");
        clearDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDatabaseButtonActionPerformed(evt);
            }
        });

        updateTableButton.setText("Update Table");
        updateTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTableButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Database");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load Database");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewDatabaseSubtitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(infoLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchEmployeeInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewEmployeeDataSubtitle)
                            .addComponent(fetchedDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(infoLabel2)
                            .addComponent(infoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loadButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(updateTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearDatabaseButton))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLabel2)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearDatabaseButton)
                            .addComponent(saveButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateTableButton)
                            .addComponent(loadButton))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDatabaseSubtitle)
                    .addComponent(viewEmployeeDataSubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchEmployeeInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fetchedDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // Add employee
        AddEmployee newWindow = new AddEmployee();
        newWindow.setVisible(true);
        System.out.println("Opened AddEmployee");
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // Update detched data
        updateFetchedDataPanel();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDatabaseButtonActionPerformed
        // TODO add your handling code here:
        clearHashTable();
    }//GEN-LAST:event_clearDatabaseButtonActionPerformed

    private void updateTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTableButtonActionPerformed
        // Updates Table
        updateTable();
    }//GEN-LAST:event_updateTableButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Save data to file
        EmployeeDatabase.getInstance().saveDatabase();
        updateTable();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // Load data from file
        EmployeeDatabase.getInstance().loadDatabase();
        updateTable();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void editEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeButtonActionPerformed
        // Edit Employee
        EditEmployee newWindow = new EditEmployee();
        newWindow.setVisible(true);
        System.out.println("Opened EditEmployee");
        updateTable();
    }//GEN-LAST:event_editEmployeeButtonActionPerformed

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeButtonActionPerformed
        // Remove Employee
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getSearchEmployees(searchEmployeeInfoField.getText(), "Employee Number");
        
        for(EmployeeInfo emp : empList) {
            EmployeeDatabase.getInstance().removeEmployee(emp);
        }
        searchEmployeeInfoField.setText("");
        updateFetchedDataPanel();
        updateTable();
    }//GEN-LAST:event_removeEmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.setRowCount(0);
        mainTable.setModel(model);
    }
    
    public void updateTable() {
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getAllEmployees();
        
        clearTable();
        
        for(EmployeeInfo emp : empList) {
            Object[] row = new Object[5];
            row[0] = String.valueOf(emp.getEmployeeNumber());
            row[1] = emp.getFirstName();
            row[2] = emp.getLastName();
            row[3] = emp.getWorkLocation();
            row[4] = emp.getDepartment();
            addRowToTable(row);
        }
    }
    
    private void updateFetchedDataPanel() {
        clearFetchedDataPanel();
        // int employeeNum = Integer.parseInt(employeeInfoField.getText());
        employeeNumber = searchEmployeeInfoField.getText();
        EmployeeDatabase.getInstance().setSearchEmployeeNumber(employeeNumber);
        
        // System.out.println(EmployeeDatabase.getInstance().getSearchEmployeeNumber());
                
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getSearchEmployees(employeeNumber, "Employee Number");
        
        System.out.println(empList);
        
        for(EmployeeInfo emp : empList) {
            
            fetchedFirstNameLabel.setText(emp.getFirstName());
            fetchedLastNameLabel.setText(emp.getLastName());
            fetchedBirthdayLabel.setText(emp.getDayBorn() + "/" + emp.getMonthBorn() + "/" + emp.getYearBorn());
            
            fetchedEmployeeNumberLabel.setText(String.valueOf(emp.getEmployeeNumber()));
            fetchedWorkLocationLabel.setText(emp.getWorkLocation());
            fetchedDepartmentLabel.setText(emp.getDepartment());
            
            switch (emp.getTypeWork().charAt(0)) {
                case 'P':
                    fetchedTypeOfWorkLabel.setText(emp.getTypeWork());
                    fetchedHourlyWageLabel.setText(String.valueOf(emp.getHourlyWage()) + "$/h");
                    fetchedHoursPerWeekLabel.setText(String.valueOf(emp.getHoursPerWeek()));
                    fetchedWeeksPerYearLabel.setText(String.valueOf(emp.getWeeksPerYear()));
                    fetchedDeductionRateLabel.setText(String.valueOf(emp.getDeductionRate()) + " %");
                    fetchedGrossYearlySalaryLabel.setText(String.valueOf(emp.getHourlyWage() * emp.getHoursPerWeek() * emp.getWeeksPerYear()) + " $/year");
                    fetchedNetYearlySalaryLabel.setText(String.valueOf(emp.getHourlyWage() * emp.getHoursPerWeek() * emp.getWeeksPerYear() / 100 * (100-emp.getDeductionRate())) + " $/year");
                    grayOutFetchedDataPanel();
                    ungrayPartTimeEmployee();
                    break;
                case 'F':
                    fetchedTypeOfWorkLabel.setText(emp.getTypeWork());
                    fetchedDeductionRateLabel.setText(String.valueOf(emp.getDeductionRate()) + " %");
                    fetchedGrossYearlySalaryLabel.setText(String.valueOf(emp.getYearlySalary()) + " $/year");
                    fetchedNetYearlySalaryLabel.setText(String.valueOf(emp.getYearlySalary() / 100 * (100-emp.getDeductionRate())) + " $/year");
                    grayOutFetchedDataPanel();
                    ungrayFullTimeEmployee();
                    break;
                default:
                    System.out.println("RIP");
                    System.out.println(":" + emp.getTypeWork() + ":");
                    break;
            }
        }
    }
    
    private void clearFetchedDataPanel() {
        fetchedFirstNameLabel.setText(" ");
        fetchedLastNameLabel.setText(" ");
        fetchedBirthdayLabel.setText(" ");

        fetchedEmployeeNumberLabel.setText(" ");
        fetchedWorkLocationLabel.setText(" ");
        fetchedDepartmentLabel.setText(" ");
        
        fetchedTypeOfWorkLabel.setText(" ");
        fetchedHourlyWageLabel.setText(" ");
        fetchedHoursPerWeekLabel.setText(" ");
        fetchedWeeksPerYearLabel.setText(" ");
        fetchedDeductionRateLabel.setText(" ");
        fetchedGrossYearlySalaryLabel.setText(" ");
        fetchedNetYearlySalaryLabel.setText(" ");
    }
    
    private void grayOutFetchedDataPanel() {
        
        firstNameLabel.setForeground(Color.GRAY);
        lastNameLabel.setForeground(Color.GRAY);
        birthdayLabel.setForeground(Color.GRAY);
        employeeNumberLabel.setForeground(Color.GRAY);
        workLocationLabel.setForeground(Color.GRAY);
        departmentLabel.setForeground(Color.GRAY);
        typeOfWorkLabel.setForeground(Color.GRAY);
        hourlyWageLabel.setForeground(Color.GRAY);
        hoursPerWeekLabel.setForeground(Color.GRAY);
        weeksPerYearLabel.setForeground(Color.GRAY);
        deductionRateLabel.setForeground(Color.GRAY);
        grossYearlySalaryLabel.setForeground(Color.GRAY);
        netYearlySalaryLabel.setForeground(Color.GRAY);
        
        editEmployeeButton.setEnabled(false);
        removeEmployeeButton.setEnabled(false);
    }
    
    private void ungrayPartTimeEmployee() {
        firstNameLabel.setForeground(Color.BLACK);
        lastNameLabel.setForeground(Color.BLACK);
        birthdayLabel.setForeground(Color.BLACK);
        employeeNumberLabel.setForeground(Color.BLACK);
        workLocationLabel.setForeground(Color.BLACK);
        departmentLabel.setForeground(Color.BLACK);
        typeOfWorkLabel.setForeground(Color.BLACK);
        hourlyWageLabel.setForeground(Color.BLACK);
        hoursPerWeekLabel.setForeground(Color.BLACK);
        weeksPerYearLabel.setForeground(Color.BLACK);
        deductionRateLabel.setForeground(Color.BLACK);
        grossYearlySalaryLabel.setForeground(Color.BLACK);
        netYearlySalaryLabel.setForeground(Color.BLACK);
        
        editEmployeeButton.setEnabled(true);
        removeEmployeeButton.setEnabled(true);
    }
    
    private void ungrayFullTimeEmployee() {
        firstNameLabel.setForeground(Color.BLACK);
        lastNameLabel.setForeground(Color.BLACK);
        birthdayLabel.setForeground(Color.BLACK);
        employeeNumberLabel.setForeground(Color.BLACK);
        workLocationLabel.setForeground(Color.BLACK);
        departmentLabel.setForeground(Color.BLACK);
        typeOfWorkLabel.setForeground(Color.BLACK);
        hourlyWageLabel.setForeground(Color.GRAY);
        hoursPerWeekLabel.setForeground(Color.GRAY);
        weeksPerYearLabel.setForeground(Color.GRAY);
        deductionRateLabel.setForeground(Color.BLACK);
        grossYearlySalaryLabel.setForeground(Color.BLACK);
        netYearlySalaryLabel.setForeground(Color.BLACK);
        
        editEmployeeButton.setEnabled(true);
        removeEmployeeButton.setEnabled(true);
    }
    
    public void addRowToTable(Object[] row) {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.addRow(row);
        mainTable.setModel(model);   
    }
    
    public void clearHashTable() {
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getAllEmployees();
        
        for(EmployeeInfo emp : empList) {
            EmployeeDatabase.getInstance().removeEmployee(emp);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JButton clearDatabaseButton;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JButton editEmployeeButton;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JPanel fPDP1;
    private javax.swing.JPanel fPDP2;
    private javax.swing.JPanel fWaDP1;
    private javax.swing.JPanel fWaDP2;
    private javax.swing.JPanel fWoDP1;
    private javax.swing.JPanel fWoDP2;
    private javax.swing.JLabel fetchedBirthdayLabel;
    private javax.swing.JPanel fetchedDataPanel;
    private javax.swing.JLabel fetchedDeductionRateLabel;
    private javax.swing.JLabel fetchedDepartmentLabel;
    private javax.swing.JLabel fetchedEmployeeNumberLabel;
    private javax.swing.JLabel fetchedFirstNameLabel;
    private javax.swing.JLabel fetchedGrossYearlySalaryLabel;
    private javax.swing.JLabel fetchedHourlyWageLabel;
    private javax.swing.JLabel fetchedHoursPerWeekLabel;
    private javax.swing.JLabel fetchedLastNameLabel;
    private javax.swing.JLabel fetchedNetYearlySalaryLabel;
    private javax.swing.JPanel fetchedPersonalDetailsPanel;
    private javax.swing.JLabel fetchedTypeOfWorkLabel;
    private javax.swing.JPanel fetchedWagelDetailsPanel;
    private javax.swing.JLabel fetchedWeeksPerYearLabel;
    private javax.swing.JPanel fetchedWorkDetailsPanel;
    private javax.swing.JLabel fetchedWorkLocationLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel grossYearlySalaryLabel;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton loadButton;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel netYearlySalaryLabel;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchEmployeeInfoField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel typeOfWorkLabel;
    private javax.swing.JButton updateTableButton;
    private javax.swing.JLabel viewDatabaseSubtitle;
    private javax.swing.JLabel viewEmployeeDataSubtitle;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JLabel workLocationLabel;
    // End of variables declaration//GEN-END:variables
}
