/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabasev4.pkg0;

/**
 *
 * @author Samuel
 */
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        initInfo();
        
        if (partTimeButton.isSelected() == true) {
            grayOutPartTimeEmployee();
        } else {
            grayOutFullTimeEmployee();
        }
    }
    
    private boolean partTime = true;
    MainMenu mMenu = new MainMenu();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeWorkButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        infoLine1 = new javax.swing.JLabel();
        infoLine2 = new javax.swing.JLabel();
        personalDetailPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        yearBornField = new javax.swing.JTextField();
        monthBornField = new javax.swing.JTextField();
        dayBornField = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        workDetailPanel = new javax.swing.JPanel();
        employeeNumberLabel = new javax.swing.JLabel();
        employeeNumberField = new javax.swing.JTextField();
        workLocationLabel = new javax.swing.JLabel();
        workLocationField = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        departmentField = new javax.swing.JTextField();
        wageDetailPanel = new javax.swing.JPanel();
        typeOfWorkLabel = new javax.swing.JLabel();
        partTimeButton = new javax.swing.JRadioButton();
        fullTimeButton = new javax.swing.JRadioButton();
        hourlyWageLabel = new javax.swing.JLabel();
        hourlyWageField = new javax.swing.JTextField();
        dollarPerHourLabel = new javax.swing.JLabel();
        hoursPerWeekLabel = new javax.swing.JLabel();
        hoursPerWeekField = new javax.swing.JTextField();
        deductionRateLabel = new javax.swing.JLabel();
        deductionRateField = new javax.swing.JTextField();
        percentLabel = new javax.swing.JLabel();
        yearlySalaryLabel = new javax.swing.JLabel();
        yearlySalaryField = new javax.swing.JTextField();
        weeksPerYearLabel = new javax.swing.JLabel();
        weeksPerYearField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        infoLine1.setText("This is where you can edit employee info in the database!");

        infoLine2.setText("Edit the following details:");

        personalDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        birthdayLabel.setText("Birthday");

        yearBornField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearBornField.setText("YYYY");
        yearBornField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearBornFieldFocusGained(evt);
            }
        });

        monthBornField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthBornField.setText("MM");
        monthBornField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthBornFieldFocusGained(evt);
            }
        });

        dayBornField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayBornField.setText("DD");
        dayBornField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dayBornFieldFocusGained(evt);
            }
        });

        yearLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLabel.setText("Year");

        monthLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLabel.setText("Month");

        dayLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        dayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayLabel.setText("Day");

        javax.swing.GroupLayout personalDetailPanelLayout = new javax.swing.GroupLayout(personalDetailPanel);
        personalDetailPanel.setLayout(personalDetailPanelLayout);
        personalDetailPanelLayout.setHorizontalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(birthdayLabel))
                .addGap(28, 28, 28)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearBornField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(monthBornField)
                            .addComponent(monthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayBornField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(dayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lastNameField)
                    .addComponent(firstNameField))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        personalDetailPanelLayout.setVerticalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(monthLabel)
                    .addComponent(dayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearBornField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthBornField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayBornField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayLabel)))
        );

        workDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        employeeNumberLabel.setText("Employee Number");

        workLocationLabel.setText("Work Location");

        departmentLabel.setText("Department");

        javax.swing.GroupLayout workDetailPanelLayout = new javax.swing.GroupLayout(workDetailPanel);
        workDetailPanel.setLayout(workDetailPanelLayout);
        workDetailPanelLayout.setHorizontalGroup(
            workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeNumberLabel)
                    .addComponent(workLocationLabel)
                    .addComponent(departmentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(workLocationField)
                    .addComponent(departmentField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workDetailPanelLayout.setVerticalGroup(
            workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNumberLabel)
                    .addComponent(employeeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workLocationLabel)
                    .addComponent(workLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentLabel)
                    .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        wageDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wage Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        typeOfWorkLabel.setText("Type of Work");

        typeWorkButtonGroup.add(partTimeButton);
        partTimeButton.setText("Part-Time");
        partTimeButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                partTimeButtonFocusGained(evt);
            }
        });
        partTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeButtonActionPerformed(evt);
            }
        });

        typeWorkButtonGroup.add(fullTimeButton);
        fullTimeButton.setText("Full-Time");
        fullTimeButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullTimeButtonFocusGained(evt);
            }
        });
        fullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeButtonActionPerformed(evt);
            }
        });

        hourlyWageLabel.setText("Hourly Wage");

        dollarPerHourLabel.setText("$/h");

        hoursPerWeekLabel.setText("Hours Per Week");

        deductionRateLabel.setText("Deduction Rate");

        percentLabel.setText("%");

        yearlySalaryLabel.setText("Yearly Salary");

        weeksPerYearLabel.setText("Weeks Per Year");

        javax.swing.GroupLayout wageDetailPanelLayout = new javax.swing.GroupLayout(wageDetailPanel);
        wageDetailPanel.setLayout(wageDetailPanelLayout);
        wageDetailPanelLayout.setHorizontalGroup(
            wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wageDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wageDetailPanelLayout.createSequentialGroup()
                        .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeOfWorkLabel)
                            .addComponent(hourlyWageLabel))
                        .addGap(30, 30, 30)
                        .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wageDetailPanelLayout.createSequentialGroup()
                                .addComponent(partTimeButton)
                                .addGap(18, 18, 18)
                                .addComponent(fullTimeButton))
                            .addGroup(wageDetailPanelLayout.createSequentialGroup()
                                .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollarPerHourLabel)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(wageDetailPanelLayout.createSequentialGroup()
                        .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoursPerWeekLabel)
                            .addComponent(deductionRateLabel)
                            .addComponent(yearlySalaryLabel)
                            .addComponent(weeksPerYearLabel))
                        .addGap(18, 18, 18)
                        .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearlySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(wageDetailPanelLayout.createSequentialGroup()
                                    .addComponent(deductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(percentLabel))
                                .addComponent(hoursPerWeekField))
                            .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        wageDetailPanelLayout.setVerticalGroup(
            wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wageDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeButton)
                    .addComponent(fullTimeButton)
                    .addComponent(typeOfWorkLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyWageLabel)
                    .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarPerHourLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursPerWeekLabel)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeksPerYearLabel)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductionRateLabel)
                    .addComponent(deductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlySalaryLabel)
                    .addComponent(yearlySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLine1)
                    .addComponent(infoLine2)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(wageDetailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workDetailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personalDetailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(submitButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLine2)
                .addGap(18, 18, 18)
                .addComponent(personalDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wageDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearBornFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearBornFieldFocusGained
        // TODO add your handling code here:
        // Removes content when selected
        yearBornField.setText("");
    }//GEN-LAST:event_yearBornFieldFocusGained

    private void monthBornFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthBornFieldFocusGained
        // TODO add your handling code here:
        // Removes content when selected
        monthBornField.setText("");
    }//GEN-LAST:event_monthBornFieldFocusGained

    private void dayBornFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayBornFieldFocusGained
        // TODO add your handling code here:
        // Removes content when selected
        dayBornField.setText("");
    }//GEN-LAST:event_dayBornFieldFocusGained

    private void partTimeButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_partTimeButtonFocusGained
        // PartTime Button Selected
        hourlyWageField.setEnabled(true);
        hoursPerWeekField.setEnabled(true);
        weeksPerYearField.setEnabled(true);
        deductionRateField.setEnabled(true);
        yearlySalaryField.setEnabled(false);

        hourlyWageLabel.setForeground(Color.BLACK);
        hoursPerWeekLabel.setForeground(Color.BLACK);
        weeksPerYearLabel.setForeground(Color.BLACK);
        deductionRateLabel.setForeground(Color.BLACK);
        yearlySalaryLabel.setForeground(Color.GRAY);

        yearlySalaryField.setText("");
    }//GEN-LAST:event_partTimeButtonFocusGained

    private void partTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeButtonActionPerformed
        partTime = true;
    }//GEN-LAST:event_partTimeButtonActionPerformed

    private void fullTimeButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullTimeButtonFocusGained
        // FullTime Button Selected
        hourlyWageField.setEnabled(false);
        hoursPerWeekField.setEnabled(false);
        weeksPerYearField.setEnabled(false);
        deductionRateField.setEnabled(true);
        yearlySalaryField.setEnabled(true);

        hourlyWageLabel.setForeground(Color.GRAY);
        hoursPerWeekLabel.setForeground(Color.GRAY);
        weeksPerYearLabel.setForeground(Color.GRAY);
        deductionRateLabel.setForeground(Color.BLACK);
        yearlySalaryLabel.setForeground(Color.BLACK);

        hourlyWageField.setText("");
        hoursPerWeekField.setText("");
        weeksPerYearField.setText("");
    }//GEN-LAST:event_fullTimeButtonFocusGained

    private void fullTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeButtonActionPerformed
        // TODO add your handling code here:

        partTime = false;
    }//GEN-LAST:event_fullTimeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        // Close Window
        this.dispose();
        System.out.println("Closed EditEmployee");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        removeEmployee();
        // Declares and reads field content
        // Wage Details
        double hourlyWage = 0;
        int hoursPerWeek = 0;
        int weeksPerYear = 0;
        double deductionRate = 0;
        double yearlySalary = 0;

        try {
            // String employeeStatus;
            // Personal Details
            String firstName = firstNameField.getText();
            String lastName = lastNameField.getText();
            String yearBorn = yearBornField.getText();
            String monthBorn = monthBornField.getText();
            String dayBorn = dayBornField.getText();

            // Work Details
            int employeeNumber = Integer.parseInt(employeeNumberField.getText());
            String workLocation = workLocationField.getText();
            String department = departmentField.getText();

            // Wage Details
            String typeWork = "";

            if (partTimeButton.isSelected()) {
                typeWork = "Part-time";
                hourlyWage = Double.parseDouble(hourlyWageField.getText());
                hoursPerWeek = Integer.parseInt(hoursPerWeekField.getText());
                weeksPerYear = Integer.parseInt(weeksPerYearField.getText());
                deductionRate = Double.parseDouble(deductionRateField.getText());
                yearlySalary = 0;

            } else if (fullTimeButton.isSelected()){
                typeWork = "Full-time";
                hourlyWage = 0;
                hoursPerWeek = 0;
                weeksPerYear = 0;
                deductionRate = Double.parseDouble(deductionRateField.getText());
                yearlySalary = Double.parseDouble(yearlySalaryField.getText());

            } else {
                // Add custom error message here later
            }

            EmployeeDatabase.getInstance().addEmployee(new NewEmployee(firstName, lastName, yearBorn, monthBorn, dayBorn, employeeNumber, workLocation, department, typeWork, hourlyWage, hoursPerWeek, weeksPerYear, deductionRate, yearlySalary));

            // Close Window
            this.dispose();
            System.out.println("Closed EditEmployee");

        } catch(IndexOutOfBoundsException|NumberFormatException e) {
            ErrorPage newWindow = new ErrorPage();
            newWindow.setVisible(true);
            System.out.println("Error occured! Opened ErrorPage");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }
    
    public void initInfo () {
        
        String employeeNumber = EmployeeDatabase.getInstance().getSearchEmployeeNumber();
        System.out.println("Emp Num: " + employeeNumber);
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getSearchEmployees(employeeNumber, "Employee Number");
        
        for(EmployeeInfo emp : empList) {
            firstNameField.setText(emp.getFirstName());
            lastNameField.setText(emp.getLastName());
            dayBornField.setText(emp.getDayBorn());
            monthBornField.setText(emp.getMonthBorn());
            yearBornField.setText(emp.getYearBorn());
            
            employeeNumberField.setText(String.valueOf(emp.getEmployeeNumber()));
            workLocationField.setText(emp.getWorkLocation());
            departmentField.setText(emp.getDepartment());
            
            // typeWorkField.setText(emp.getTypeWork());
            switch (emp.getTypeWork().charAt(0)) {
                case 'P':
                    partTimeButton.setSelected(true);
                    fullTimeButton.setSelected(false);
                    break;
                case 'F':
                    partTimeButton.setSelected(false);
                    fullTimeButton.setSelected(true);
                    break;
                default:
                    System.out.println("RIP");
                    System.out.println(":" + emp.getTypeWork() + ":");
                    break;
            }
            
            
            hourlyWageField.setText(String.valueOf(emp.getHourlyWage()));
            hoursPerWeekField.setText(String.valueOf(emp.getHoursPerWeek()));
            weeksPerYearField.setText(String.valueOf(emp.getWeeksPerYear()));
            deductionRateField.setText(String.valueOf(emp.getDeductionRate()));
            yearlySalaryField.setText(String.valueOf(emp.getYearlySalary()));
        }
    }
    
    public void removeEmployee() {
        // Remove Employee
        ArrayList<EmployeeInfo> empList = EmployeeDatabase.getInstance().getSearchEmployees(EmployeeDatabase.getInstance().getSearchEmployeeNumber(), "Employee Number");
        
        for(EmployeeInfo emp : empList) {
            EmployeeDatabase.getInstance().removeEmployee(emp);
        }
    }
    
    private void grayOutPartTimeEmployee() {
        hourlyWageField.setEnabled(true);
        hoursPerWeekField.setEnabled(true);
        weeksPerYearField.setEnabled(true);
        deductionRateField.setEnabled(true);
        yearlySalaryField.setEnabled(false);
        
        hourlyWageLabel.setForeground(Color.BLACK);
        hoursPerWeekLabel.setForeground(Color.BLACK);
        weeksPerYearLabel.setForeground(Color.BLACK);
        deductionRateLabel.setForeground(Color.BLACK);
        percentLabel.setForeground(Color.BLACK);
        yearlySalaryLabel.setForeground(Color.GRAY);
        
        yearlySalaryField.setText("");
    }
    
    private void grayOutFullTimeEmployee() {
        hourlyWageField.setEnabled(false);
        hoursPerWeekField.setEnabled(false);
        weeksPerYearField.setEnabled(false);
        deductionRateField.setEnabled(true);
        yearlySalaryField.setEnabled(true);
        
        hourlyWageLabel.setForeground(Color.GRAY);
        hoursPerWeekLabel.setForeground(Color.GRAY);
        weeksPerYearLabel.setForeground(Color.GRAY);
        deductionRateLabel.setForeground(Color.BLACK);
        percentLabel.setForeground(Color.BLACK);
        yearlySalaryLabel.setForeground(Color.BLACK);
        
        hourlyWageField.setText("");
        hoursPerWeekField.setText("");
        weeksPerYearField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dayBornField;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField deductionRateField;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JTextField departmentField;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel dollarPerHourLabel;
    private javax.swing.JTextField employeeNumberField;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JRadioButton fullTimeButton;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JLabel infoLine1;
    private javax.swing.JLabel infoLine2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField monthBornField;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JRadioButton partTimeButton;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JPanel personalDetailPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel typeOfWorkLabel;
    private javax.swing.ButtonGroup typeWorkButtonGroup;
    private javax.swing.JPanel wageDetailPanel;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JPanel workDetailPanel;
    private javax.swing.JTextField workLocationField;
    private javax.swing.JLabel workLocationLabel;
    private javax.swing.JTextField yearBornField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearlySalaryField;
    private javax.swing.JLabel yearlySalaryLabel;
    // End of variables declaration//GEN-END:variables
}
